apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: message
  template:
    metadata:
      labels:
        app: message
    spec:
      containers:
        - name: message
          image: docker.io/popelolole/message-service:latest
          env:
            - name: MYSQL_HOST
              value: mysql-service
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: journalapp_user
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: journaldb
---
apiVersion: v1
kind: Service
metadata:
  name: message-service
spec:
  selector:
    app: message
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort